name: Plugin Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Plugin Test
    steps:
      - uses: actions/checkout@v3
      - name: Download and test a plugin
        run: |
          svn co https://plugins.svn.wordpress.org/hello-dolly/trunk ./hello-dolly
      - uses: ./
        with:
          type: plugin