name: Theme Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Theme Test
    steps:
      - uses: actions/checkout@v3
      - name: Download and test a theme
        run: |
          svn co https://themes.svn.wordpress.org/twentytwentyone/trunk ./twentytwentyone
      - uses: ./
        with:
          type: theme